### ISSUE TITLE
「Suggestion」brokers 设置为 null

### ISSUE THREAD

**Issue by yansongda** [swoole/phpkafka#41]
看到支持 bootstrap_server，所以，想着能否将 brokers 直接设置为 null

于是看了代码，发现代码中是支持的：https://github.com/longyan/phpkafka/blob/master/src/Broker.php#L71

因此，麻烦看看，能否

1. https://github.com/longyan/phpkafka/blob/master/src/Consumer/ConsumerConfig.php#L26
2. https://github.com/longyan/phpkafka/blob/master/src/Producer/ProducerConfig.php#L27
3. 文档

的注释或文档中，加上 null 同时说明下咧

PS: 实际测试也是 ok 的

非常感谢

**Comment by Yurunsoft** [comment]
感谢建议~
