### ISSUE TITLE
Sasl 相关的代码现在composer的包无法拉取到

### ISSUE THREAD

**Issue by jackwangshukai** [swoole/phpkafka#51]
* 你遇到了什么问题？
Sasl 相关的代码现在composer的包无法拉取到 是不是没发版

* Kafka 环境是自建还是云服务？

阿里云

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep longlang/phpkafka`

```
# 粘贴到这里

```

* 提供最小可复现代码：

```php
// 你的代码

```

**Comment by Yurunsoft** [comment]
已发版
