### ISSUE TITLE
Authentication using the SCRAM-SHA-512 mechanism

### ISSUE THREAD

**Issue by Rishat7c** [swoole/phpkafka#73]
* What problem did you encounter?

Can you show an example of authentication using the SCRAM-SHA-512 mechanism? (with SASL_SSL)

An example from the cloud service documentation looks like this
```
kafkacat -C \
          -b adress:9091 \
          -t topic \
          -X security.protocol=SASL_SSL\
          -X sasl.mechanisms=SCRAM-SHA-512 \
          -X sasl.username="user login" \
          -X sasl.password="consumer password" \
          -X ssl.ca.location=/usr/local/share/ca-certificates/Yandex/YandexCA.crt -Z -K:
```

* Is the Kafka environment self-built or cloud service?

cloud service

* Please execute the following command to get environment information.
> `php -v & php --ri swoole & composer info | grep longlang/phpkafka`

PHP 7.4.30 (cli) (built: Jun  7 2022 08:38:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies
longlang/phpkafka          dev-master f154746 A kafka client. Support php-fpm and Swoole.

**Comment by Rishat7c** [comment]
Switched to php-rdkafka. There were no problems. Can be closed

**Comment by wuxi889** [comment]
@Rishat7c hi, How to verify scram-sha-512 with rdkafka in swoole?

**Comment by Jeckerson** [comment]
@wuxi889 Here is example of my implementation of this mechanism
https://github.com/Jeckerson/phpkafka/commit/c2badad88559dde68e9aefa0e2ed067aba401e50
